### ISSUE TITLE
db-oracle installation on ubuntu 11 and Oracle 11g R2 

### ISSUE THREAD

**Issue by amosunfemi** [mariano/node-db-oracle#11]
hi!

Pls I got this error when I ran npm db-oracle install

npm db-oracle install

node.js:63
    throw e;
    ^
Error: Cannot find module '../lib/utils/log'
    at loadModule (node.js:275:15)
    at require (node.js:411:14)
    at /home/amosun/bin/npm:3:11
    at Object.<anonymous> (/home/amosun/bin/npm:65:2)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at Object.runMain (node.js:522:24)
    at Array.<anonymous> (node.js:756:12)
    at EventEmitter._tickCallback (node.js:55:22)

I dont knwo if am missing a module, or something.

Thanks

**Comment by yanko** [comment]
use this 
npm install db-oracle
and you should see a result like this:

> db-oracle@0.2.2 preuninstall /node_modules/db-oracle
> rm -rf build/*
> 
> db-oracle@0.2.2 install /node_modules/db-oracle
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /node 
Checking for node prefix                 : ok /usr/local 
Checking for header occi.h               : yes 
Checking for library occi                : yes 
'configure' finished successfully (0.400s)
Waf: Entering directory `/node_modules/db-oracle/build'
[ 1/12] cxx: lib/node-db/binding.cc -> build/Release/lib/node-db/binding_1.o
[ 2/12] cxx: lib/node-db/connection.cc -> build/Release/lib/node-db/connection_1.o
[ 3/12] cxx: lib/node-db/events.cc -> build/Release/lib/node-db/events_1.o
[ 4/12] cxx: lib/node-db/exception.cc -> build/Release/lib/node-db/exception_1.o
[ 5/12] cxx: lib/node-db/query.cc -> build/Release/lib/node-db/query_1.o
[ 6/12] cxx: lib/node-db/result.cc -> build/Release/lib/node-db/result_1.o
[ 7/12] cxx: src/connection.cc -> build/Release/src/connection_1.o
[ 8/12] cxx: src/oracle.cc -> build/Release/src/oracle_1.o
[ 9/12] cxx: src/query.cc -> build/Release/src/query_1.o
[10/12] cxx: src/result.cc -> build/Release/src/result_1.o
[11/12] cxx: src/oracle_bindings.cc -> build/Release/src/oracle_bindings_1.o
[12/12] cxx_link: build/Release/lib/node-db/binding_1.o build/Release/lib/node-db/connection_1.o build/Release/lib/node-db/events_1.o build/Release/lib/node-db/exception_1.o build/Release/lib/node-db/query_1.o build/Release/lib/node-db/result_1.o build/Release/src/connection_1.o build/Release/src/oracle_1.o build/Release/src/query_1.o build/Release/src/result_1.o build/Release/src/oracle_bindings_1.o -> build/Release/oracle_bindings.node
Waf: Leaving directory`/node_modules/db-oracle/build'
'build' finished successfully (4.373s)
db-oracle@0.2.2 /node_modules/db-oracle

**Comment by sameersegal** [comment]
What version of Waf are you using? And how did you install it?

I tried the binary waf-1.7.10 and got some errors to do with the verbose switch. 

Then I tried waf-1.6.11 and got the following:

```
> db-oracle@0.2.3 install /root/Code/test/HM/node_modules/db-oracle
> node-waf configure build

compat: rename "set_options" to "options" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
compat: rename "srcdir" to "top" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
compat: rename "blddir" to "out" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
compat: rename "set_options" to "options" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
compat: rename "srcdir" to "top" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
compat: rename "blddir" to "out" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
compat: rename "set_options" to "options" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
compat: rename "srcdir" to "top" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
compat: rename "blddir" to "out" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
Setting top to                           : /root/Code/test/HM/node_modules/db-oracle
Setting out to                           : /root/Code/test/HM/node_modules/db-oracle/build
compat: rename "set_options" to "options" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
compat: rename "srcdir" to "top" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
compat: rename "blddir" to "out" ('/root/Code/test/HM/node_modules/db-oracle/wscript')
Checking for 'g++' (c++ compiler)        : /usr/bin/g++
Could not load the Waf tool 'node_addon' from ['/usr/bin/.waf-1.6.11-30618c54883417962c38f5d395f83584', '/usr/bin', '/usr/lib/python2.6', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-tk', '/usr/lib/python2.6/lib-old', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages', '/usr/lib/pymodules/python2.6', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/local/lib/python2.6/dist-packages'] (try the --download option?):
No module named node_addon
(complete log in /root/Code/test/HM/node_modules/db-oracle/build/config.log)
```

The log file does not exist
