### ISSUE TITLE
Cannot install on debian

### ISSUE THREAD

**Issue by amirotin** [mariano/node-db-oracle#14]
Using latest oracle instantclient 11.2.0.3.0 x86 get the following error:

``` javascript
[1/2] [32mcxx: build/.conf_check_0/test.cpp -> build/.conf_check_0/testbuild/Release/test_1.o
[0m['/usr/bin/g++', '-g', '-Wall', '-I/opt/instantclient/sdk/include/', '../test.cpp', '-c', '-o', 'Release/test_1.o']
[2/2] [33mcxx_link: build/.conf_check_0/testbuild/Release/test_1.o -> build/.conf_check_0/testbuild/Release/testprog
[0m/usr/bin/ld: cannot find -locci
collect2: ld returned 1 exit status
['/usr/bin/g++', 'Release/test_1.o', '-o', '/var/claimweb/node-db-oracle/build/.conf_check_0/testbuild/Release/testprog', '-L/opt/instantclient', '-locci', '-lclntsh', '-lnnz11']
command returned 'Build failed:  -> task failed (err #1): \n\t{task: cxx_link test_1.o -> testprog}'Missing include files for OCI
```

Instantclient is located in /opt/instantclient

**Comment by mariano** [comment]
Can you do a:

``` bash
$ ls -la /opt/instantclient
```

Because this line:

``` bash
/usr/bin/ld: cannot find -locci
```

Tells you it's not finding libocci. If you see libocci.so in /opt/instantclient, try doing:

``` bash
$ sudo ldconfig
```

And then re-installing db-oracle.

**Comment by amirotin** [comment]
It;s ok now. I've  libocci.so.11.1. Just created symlink

2011/11/11 Mariano Iglesias <
reply@reply.github.com>

**Comment by mariano** [comment]
Can you post what you did on this ticket so others with similar problems can see the solution?

**Comment by mariano** [comment]
Closing this

**Comment by amirotin** [comment]
Check if you have some libs with extension different to .so (.so.11.1 for
example) and just do symbolic link ( ln -s /opt/instantclient/
libocci.so.11.1 /opt/instanyclient/libocci.so)

2011/11/11 Mariano Iglesias <
reply@reply.github.com>
