### ISSUE TITLE
slow result sets

### ISSUE THREAD

**Issue by troyk** [mariano/node-db-oracle#15]
It seems anything beyond nominal result sets takes an extremely long time.  The query below (500 rows of 3 columns) completes with ruby's activerecord in 1.4 seconds, while node takes about 34 seconds.  If I limit the rows to 10, node it will run in .8 seconds.  During the 34 seconds, node is not doing much, sitting idle barely hitting RAM or CPU.

I turned casting off to see if it would make a difference, it doesn't

``` javascript
    var startAt;
    server.query().execute('SELECT "ORDER_NO","CUSTOMER_PO_NO","PRIMARY_CONTACT" FROM SF_RH_CUST_HEADER WHERE ROWNUM <= 500',[],function(err,rows){
      console.log(rows);
    },{
        async:true, 
        cast:false, 
        finish:function(){
          console.log('seconds: ', (new Date()-startAt)/1000);
        },
        start:function(){
          console.log('start: ',startAt = new Date());
        }
      }
    );

```

**Comment by troyk** [comment]
I've noticed that other drivers such as JDBC and Ruby's Sequel allow a prefetch option to control how many rows are prefetched from the server, so my guess is that the node driver is just getting 1 row per trip to the server.  I searched the source, and 

``` c
bool node_db_oracle::Result::isBuffered() const throw() {
    return false;
}
```

looks like this is might be intentional for now?

**Comment by tobysmith** [comment]
I had similar problems and added this

this->statement->setPrefetchRowCount(100);

before the query gets executed. Improved the performance quite a bit for me.

**Comment by troyk** [comment]
@spiralsphere Thanks alot, that's exactly what I was looking for.  I thought it didn't exist, how did you find it?

**Comment by tobysmith** [comment]
@troyk No problem. Looked up the Oracle C++ Call Interface Programmer's Guide -www.docs.oracle.com/cd/B28359_01/appdev.111/b28390/relational.htm which mentions prefetch under the heading Optimizing Performance by Setting Prefetch Count. However, it's quite short and doesn't really explain where to call the method from.

After some googling found this StackOverflow thread which gave me the answer - http://stackoverflow.com/questions/5933986/oci-in-php-much-faster-than-occi
