### ISSUE TITLE
require('db-oracle'); returns an error

### ISSUE THREAD

**Issue by yanko** [mariano/node-db-oracle#18]
Any Idea why this would happen?
spent all most whole day messing around and could not get it to work! 

> var oracle = require('db-oracle');
> TypeError: Cannot read property 'prototype' of undefined
>     at extend (/node_modules/db-oracle/db-oracle.js:23:15)
>     at Object.<anonymous> (/node_modules/db-oracle/db-oracle.js:38:17)
>     at Module._compile (module.js:432:26)
>     at Object..js (module.js:450:10)
>     at Module.load (module.js:351:31)
>     at Function._load (module.js:310:12)
>     at Module.require (module.js:357:17)
>     at require (module.js:368:17)
>     at repl:1:14
>     at REPLServer.eval (repl.js:80:21)

please help!
thankx!

**Comment by yanko** [comment]
Hey Mariano, do you think we could use db-oracle on windows??

the above issue got fixed as soon as i rebooted the machine!!!!

**Comment by mariano** [comment]
No plans yet for windows support, but will come soon!
