### ISSUE TITLE
execute query crash

### ISSUE THREAD

**Issue by andrewjs** [mariano/node-db-oracle#2]
When I  executes a simple query,nodejs crashed. 
this.query().select(' count(*) ').from('TB_DEPT').execute(function(error, rows) {
        if (error) {
            return console.log('ERROR: ' + error);
        }
       console.log(rows.length + ' ROWS');
    });

**\* glibc detected **\* ./node: free(): invalid pointer: 0x0000000001e5f720 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3a8f27245f]
/lib64/libc.so.6(cfree+0x4b)[0x3a8f2728bb]
/usr/lib64/libstdc++.so.6(_ZNSsD1Ev+0x3a)[0x3a95a9dbca]
/opt/node_modules/db-oracle/build/default/oracle_bindings.node(_ZN14node_db_oracle6Result3rowEPm+0x6d2)[0x2ad1c302a41e]
/opt/node_modules/db-oracle/build/default/oracle_bindings.node(_ZN14node_db_oracle6ResultC1EPN6oracle4occi9StatementE+0x69f)[0x2ad1c302b131]
/opt/node_modules/db-oracle/build/default/oracle_bindings.node(_ZNK14node_db_oracle10Connection5queryERKSs+0x52)[0x2ad1c3026ca6]
/opt/node_modules/db-oracle/build/default/oracle_bindings.node(_ZNK7node_db5Query7executeEv+0x47)[0x2ad1c301403d]
/opt/node_modules/db-oracle/build/default/oracle_bindings.node(_ZN7node_db5Query10eioExecuteEP7eio_req+0x86)[0x2ad1c3019cee]
./node[0x533f0b]
/lib64/libpthread.so.0[0x3a8fe0673d]
/lib64/libc.so.6(clone+0x6d)[0x3a8f2d40cd]

**Comment by andrewjs** [comment]
oracle client 10g2 static linked with libc.so.5.
here is libc.so.6

**Comment by mariano** [comment]
@andrewjs: so using oracle client 11g instead, or downgrading your libc fixed the issue?

Also, whenever you find a crash try running the script with gdb. For example if your script is called test.js, like so:

$ gdb --args node test.js

Then at the gdb> prompt, type (gdb> here is the prompt, you should not type that):

gdb> run
(You should see the crash now)
gdb> bt

Then after the bt command, you should be given a more useful backtrace, which will help me a lot during debugging.
