### ISSUE TITLE
Build node-db-oracle on Debian with Oracle 10xe 

### ISSUE THREAD

**Issue by smuellner** [mariano/node-db-oracle#27]
Hi,

I tried to build node-db-oracle on a debian system, the instantclient path output looks like this:

<pre>
HOSTNAME:/opt/node# ls -la  $OCI_INCLUDE_DIR $OCI_LIB_DIR
/opt/instantclient/lib/:
insgesamt 100164
drwxr-xr-x 2 root root     4096 16. Mär 18:35 .
drwxr-xr-x 4 root root     4096 16. Mär 18:30 ..
-rw-rw-r-- 1 root root      222 19. Apr 2010  BASIC_README
-r--r--r-- 1 root root  1621582 19. Apr 2010  classes12.jar
-rwxrwxr-x 1 root root    67582 19. Apr 2010  genezi
lrwxrwxrwx 1 root root       17 16. Mär 18:35 libclntsh.so -> libclntsh.so.10.1
-rwxrwxr-x 1 root root 19235764 19. Apr 2010  libclntsh.so.10.1
-r-xr-xr-x 1 root root  5659007 19. Apr 2010  libnnz10.so
lrwxrwxrwx 1 root root       15 16. Mär 18:35 libocci.so -> libocci.so.10.1
-rwxrwxr-x 1 root root  1403708 19. Apr 2010  libocci.so.10.1
-rwxrwxr-x 1 root root 72726010 19. Apr 2010  libociei.so
-r-xr-xr-x 1 root root   120843 19. Apr 2010  libocijdbc10.so
-r--r--r-- 1 root root  1569316 19. Apr 2010  ojdbc14.jar

/opt/instantclient/sdk/include/:
insgesamt 1500
drwxrwxr-x 2 root root   4096 19. Apr 2010  .
drwxrwxr-x 4 root root   4096 19. Apr 2010  ..
-r--r--r-- 1 root root  33230 19. Apr 2010  nzerror.h
-r--r--r-- 1 root root  85310 19. Apr 2010  nzt.h
-r--r--r-- 1 root root  11600 19. Apr 2010  occiAQ.h
-r--r--r-- 1 root root  38724 19. Apr 2010  occiCommon.h
-r--r--r-- 1 root root  73063 19. Apr 2010  occiControl.h
-r--r--r-- 1 root root  35218 19. Apr 2010  occiData.h
-r--r--r-- 1 root root   2115 19. Apr 2010  occi.h
-r--r--r-- 1 root root  29307 19. Apr 2010  occiObjects.h
-r-xr-xr-x 1 root root   7155 19. Apr 2010  oci1.h
-r--r--r-- 1 root root  10361 19. Apr 2010  oci8dp.h
-r--r--r-- 1 root root 411221 19. Apr 2010  ociap.h
-r-xr-xr-x 1 root root   6055 19. Apr 2010  ociapr.h
-r--r--r-- 1 root root  43225 19. Apr 2010  ocidef.h
-r-xr-xr-x 1 root root   4014 19. Apr 2010  ocidem.h
-r--r--r-- 1 root root  11331 19. Apr 2010  ocidfn.h
-r--r--r-- 1 root root   8954 19. Apr 2010  ociextp.h
-r--r--r-- 1 root root 153066 19. Apr 2010  oci.h
-r-xr-xr-x 1 root root   6638 19. Apr 2010  ocikpr.h
-r--r--r-- 1 root root   4351 19. Apr 2010  ocixmldb.h
-r--r--r-- 1 root root  19099 19. Apr 2010  odci.h
-r-xr-xr-x 1 root root   6605 19. Apr 2010  oratypes.h
-r--r--r-- 1 root root  15031 19. Apr 2010  orid.h
-r--r--r-- 1 root root 102726 19. Apr 2010  ori.h
-r--r--r-- 1 root root 157674 19. Apr 2010  orl.h
-r--r--r-- 1 root root  42626 19. Apr 2010  oro.h
-r--r--r-- 1 root root 116591 19. Apr 2010  ort.h
-r-xr-xr-x 1 root root   9520 19. Apr 2010  xa.h
</pre>

output for the build, using "node-waf"

<pre>
HOSTNAME:/opt/node/node_modules/db-oracle# node-waf configure build --verbose
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
Checking for header occi.h               : 18:40:06 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/opt/instantclient/sdk/include/', '../test.cpp', '-c', '-o', 'Release/test_1.o']
18:40:07 runner system command -> ['/usr/bin/g++', 'Release/test_1.o', '-o', '/opt/node/node_modules/db-oracle/build/.conf_check_0/testbuild/Release/testprog', '-L/opt/instantclient/lib/', '-locci', '-lclntsh', '-lnnz11']
Missing include files for OCI 
/opt/node/node_modules/db-oracle/wscript:42: error: the configuration failed (see '/opt/node/node_modules/db-oracle/build/config.log')
</pre>

any ideas - what I am doing wrong?

**Comment by mariano** [comment]
See the new README
