### ISSUE TITLE
db-oracle Mac OS X installation

### ISSUE THREAD

**Issue by josecardozo** [mariano/node-db-oracle#3]
Hello, 

I'm trying to use your driver (oracle) but every time that I run the command
npm install db-oracle

turns a error message like this:

> db-oracle@0.1.2 install /Users/ricky/node_modules/db-oracle
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /Users/ricky/local/node-v0.4.8 
Checking for header occi.h               : Missing include files for OCI 
/Users/ricky/node_modules/db-oracle/wscript:42: error: the configuration failed (see '/Users/ricky/node_modules/db-oracle/build/config.log')
npm ERR! error installing db-oracle@0.1.2 Error: db-oracle@0.1.2 install: `node-waf configure build`
npm ERR! error installing db-oracle@0.1.2 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing db-oracle@0.1.2     at ChildProcess.<anonymous> (/Users/ricky/local/node-v0.4.8/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing db-oracle@0.1.2     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing db-oracle@0.1.2     at ChildProcess.onexit (child_process.js:192:12)

> db-oracle@0.1.2 preuninstall /Users/ricky/node_modules/db-oracle
> rm -rf build/*

npm ERR! db-oracle@0.1.2 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the db-oracle@0.1.2 install script.
npm ERR! This is most likely a problem with the db-oracle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-oracle
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/Users/ricky/local/node/bin/npm" "install" "db-oracle"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ricky/npm-debug.log
npm not ok

Yeah, I know... theres something with the env variable 'OCI_INCLUDE_DIR'. But the problem is that the two needed env variables are setted. And the files are in /opt/instantclient/sdk/include (occi.h) and /opt/instantclient/.
Do you know what else could be wrong?

Thank you
Regards.

**Comment by mariano** [comment]
Could you do an ls -la of $OCI_INCLUDE_DIR and $OCI_LIB_DIR?

Also get inside the db-oracle directory and run:

``` bash
$ node-waf configure build --verbose
```

and paste the output

**Comment by josecardozo** [comment]
Sure, here we go:

ls -la in /opt/instantclient ($OCI_LIB_DIR):

drwxr-xr-x  13 ricky  staff       442 28 Jun 14:09 .
drwxr-xr-x   4 root   admin       136 28 Jun 13:59 ..
-rw-r--r--@  1 ricky  staff       278  1 Abr  2009 BASIC_README
-r--r--r--@  1 ricky  staff   1609607  2 Fev  2008 classes12.jar
-rwxr-xr-x@  1 ricky  staff     30556  1 Abr  2009 genezi
-rwxr-xr-x@  1 ricky  staff  21537536 31 Mar  2009 libclntsh.dylib.10.1
-rwxr-xr-x@  1 ricky  staff   1683924 11 Fev  2009 libnnz10.dylib
-rwxr-xr-x@  1 ricky  staff   1142284 11 Fev  2009 libocci.dylib.10.1
-rwxr-xr-x@  1 ricky  staff  72626824  1 Abr  2009 libociei.dylib
-rwxr-xr-x@  1 ricky  staff    106184 25 Mar  2009 libocijdbc10.dylib
-rwxr-xr-x@  1 ricky  staff    106184 25 Mar  2009 libocijdbc10.jnilib
-r--r--r--@  1 ricky  staff   1555682  2 Fev  2008 ojdbc14.jar
drwxr-xr-x@  7 ricky  staff       238  1 Abr  2009 sdk

ls -la in /opt/instantclient/sdk/include ($OCI_INCLUDE_DIR):

drwxr-xr-x@ 29 ricky  staff     986  1 Abr  2009 .
drwxr-xr-x@  7 ricky  staff     238  1 Abr  2009 ..
-r--r--r--@  1 ricky  staff   33230  8 Fev  2005 nzerror.h
-r--r--r--@  1 ricky  staff   85310 11 Out  2004 nzt.h
-r--r--r--@  1 ricky  staff    2115 15 Out  2002 occi.h
-r--r--r--@  1 ricky  staff   11600  3 Mar  2004 occiAQ.h
-r--r--r--@  1 ricky  staff   38724 27 Jan  2006 occiCommon.h
-r--r--r--@  1 ricky  staff   73063 11 Jan  2005 occiControl.h
-r--r--r--@  1 ricky  staff   35218  9 Nov  2004 occiData.h
-r--r--r--@  1 ricky  staff   29307 11 Jun  2007 occiObjects.h
-r--r--r--@  1 ricky  staff  152599 31 Out  2007 oci.h
-r--r--r--@  1 ricky  staff    7155  7 Mai  1998 oci1.h
-r--r--r--@  1 ricky  staff   10361 19 Mar  2004 oci8dp.h
-r--r--r--@  1 ricky  staff  411221 11 Jul  2006 ociap.h
-r--r--r--@  1 ricky  staff    6055 31 Mai  2000 ociapr.h
-r--r--r--@  1 ricky  staff   43225  7 Jul  2003 ocidef.h
-r--r--r--@  1 ricky  staff    4014 13 Mai  1999 ocidem.h
-r--r--r--@  1 ricky  staff   11331 24 Dez  2002 ocidfn.h
-r--r--r--@  1 ricky  staff    8954  7 Jul  2003 ociextp.h
-r--r--r--@  1 ricky  staff    6638  5 Dez  2000 ocikpr.h
-r--r--r--@  1 ricky  staff    4351 30 Jan  2004 ocixmldb.h
-r--r--r--@  1 ricky  staff   19099  5 Mai  2003 odci.h
-r--r--r--@  1 ricky  staff    6506  1 Nov  2007 oratypes.h
-r--r--r--@  1 ricky  staff  102726  7 Jul  2003 ori.h
-r--r--r--@  1 ricky  staff   15031  7 Jul  2003 orid.h
-r--r--r--@  1 ricky  staff  157674  7 Jul  2003 orl.h
-r--r--r--@  1 ricky  staff   42626  9 Jun  2003 oro.h
-r--r--r--@  1 ricky  staff  116591  7 Jul  2003 ort.h
-r--r--r--@  1 ricky  staff    9520 14 Set  1999 xa.h

$ node-waf configure build --verbose
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /Users/ricky/local/node-v0.4.8 
Checking for header occi.h               : 17:10:15 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/opt/instantclient/sdk/include', '../test.cpp', '-c', '-o', 'default/test_1.o']
17:10:15 runner system command -> ['/usr/bin/g++', 'default/test_1.o', '-o', '/Users/ricky/Desenvolvimento/node-db-oracle/build/.conf_check_0/testbuild/default/testprog', '-L/opt/instantclient', '-locci', '-lclntsh']
Missing include files for OCI 
/Users/ricky/Desenvolvimento/node-db-oracle/wscript:42: error: the configuration failed (see '/Users/ricky/Desenvolvimento/node-db-oracle/build/config.log')

Thanks!

**Comment by mariano** [comment]
I think the poblem is that it's not finding the libocci nor libclntsh files. I see from your /opt/instantclient that you have a bunch of dylib files, including the ones for libocci and libclntsh.

I'm not a Mac expert. I don't use Macs, and it bothers me they don't allow me to install a virtual machine to test this kind of suff, so I'll be helping you "blind-folded".

Ayway try doing this:

``` bash
$ export DYLD_LIBRARY_PATH=/opt/instantclient
```

Now run the build with verbose again:

``` bash
$ node-waf configure build --verbose
```

**Comment by josecardozo** [comment]
Ok, thanks for the help.
I try it... but the result is the same.

$ export DYLD_LIBRARY_PATH=/opt/instantclient

$ node-waf configure build --verbose
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /Users/ricky/local/node-v0.4.8 
Checking for header occi.h               : 17:21:17 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/opt/instantclient/sdk/include', '../test.cpp', '-c', '-o', 'default/test_1.o']
17:21:18 runner system command -> ['/usr/bin/g++', 'default/test_1.o', '-o', '/Users/ricky/Desenvolvimento/node-db-oracle/build/.conf_check_0/testbuild/default/testprog', '-L/opt/instantclient', '-locci', '-lclntsh']
Missing include files for OCI 
/Users/ricky/Desenvolvimento/node-db-oracle/wscript:42: error: the configuration failed (see '/Users/ricky/Desenvolvimento/node-db-oracle/build/config.log')

It looks like there's something wrong in the line 42 of wscript: 
conf.check(header_name="occi.h", errmsg="Missing include files for OCI", mandatory=True)

As it can't see the occi.h file in the directory. It's weird.

**Comment by mariano** [comment]
No, if you look at the actual runner command:

['/usr/bin/g++', 'default/test_1.o', '-o', '/Users/ricky/Desenvolvimento/node-db-oracle/build/.conf_check_0/testbuild/default/testprog', '-L/opt/instantclient', '-locci', '-lclntsh']

it's not exactly the header, but the library that's failing. In fact this is documented in different posts, such as [this](http://forums.oracle.com/forums/thread.jspa?threadID=966205&tstart=0) and [this](http://forums.oracle.com/forums/thread.jspa?threadID=686407).

It has to do with how Mac's dynamic libraries are loaded. For example [this post](http://www.digitalsanctum.com/2007/07/26/installing-oracle-instant-client-on-mac-os-x/) recommends that you set DYLD_LIBRARY_PATH in your profile, and source it. Could you take a look at some of the recommendations in that post? Actually after a quick read this seems interesting:

``` bash
$ cd /opt/instantclient
$ ln -s libclntsh.dylib.10.1 libclntsh.dylib
$ ln -s libocci.dylib.10.1 libocci.dylib
```

After the above, once again do:

``` bash
$ export DYLD_LIBRARY_PATH=/opt/instantclient
$ node-waf configure build --verbose
```

**Comment by mariano** [comment]
If the above doesn't work, try also creating symlinks for so:

``` bash
$ cd /opt/instantclient
$ ln -s libclntsh.dylib.10.1 libclntsh.so
$ ln -s libocci.dylib.10.1 libocci.so
```

Then without doing the DYLD_LIBRARY_PATH export, run node-waf configure build --verbose again.

If this doesn't work either, you may want to remove the .so symlinks.

**Comment by josecardozo** [comment]
Ok, thank you! 
Actually after use your first suggestion (making the links and using DYLD_LIBRARY_PATH), all that I need to do was 
npm install db-oracle 
and everything goes fine.
Best regards.
