### ISSUE TITLE
db-oracle crashed on ubuntu 10.04, Oracle 10gR2 client

### ISSUE THREAD

**Issue by mvtm** [mariano/node-db-oracle#4]
Got:
mvtm@28-moskalyov:/tmp/oradb$ gdb --args node test.js
GNU gdb (GDB) 7.1-ubuntu
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i486-linux-gnu".
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/...
Reading symbols from /usr/bin/node...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/node test.js
[Thread debugging using libthread_db enabled]
[New Thread 0xb5f45b70 (LWP 8735)]

Program received signal SIGABRT, Aborted.
0x0012d422 in __kernel_vsyscall ()
(gdb) bt
#0  0x0012d422 in __kernel_vsyscall ()
#1  0x00457651 in raise () from /lib/tls/i686/cmov/libc.so.6
#2  0x0045aa82 in abort () from /lib/tls/i686/cmov/libc.so.6
#3  0x015b0db5 in __cxxabiv1::__terminate(void (*)()) () from /usr/lib/libstdc++.so.5
#4  0x015b0df2 in std::terminate() () from /usr/lib/libstdc++.so.5
#5  0x015b0f32 in __cxa_throw () from /usr/lib/libstdc++.so.5
#6  0x006b2e95 in destr_detour0 () from /opt/oracle/product/10.2.0/client_1/lib/libocci.so.10.1
#7  0x0064e65a in Connection (this=0x85cdc10) at ../src/connection.cc:9
#8  0x0064ed39 in Oracle (this=0x85cdc88) at ../src/oracle.cc:7
#9  0x0064f151 in node_db_oracle::Oracle::New (args=...) at ../src/oracle.cc:34
#10 0x081b800d in ?? ()

**Comment by mvtm** [comment]
Seems like a oracle bug.

**Comment by mariano** [comment]
How did you end up solving it? Or was it a temporary issue?

**Comment by mvtm** [comment]
No, I can't solve this.
