### ISSUE TITLE
db-oracle installation problem with instant client 11.2.0.2

### ISSUE THREAD

**Issue by mvtm** [mariano/node-db-oracle#5]
got Missing include files for OCI.
In config.log got next few lines:
--- cut ---
build/.conf_check_0/test.cpp -> build/.conf_check_0/testbuild/default/test_1.o
[0m['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/oracle/11.2/client', '../test.cpp', '-c', '-o', 'default/test_1.o']
[2/2] [33mcxx_link: build/.conf_check_0/testbuild/default/test_1.o -> build/.conf_check_0/testbuild/default/testprog
[0m/usr/bin/ld: warning: libnnz11.so, needed by /usr/lib/oracle/11.2/client/lib//libclntsh.so, not found (try using -rpath or -rpath-link)
/usr/lib/oracle/11.2/client/lib//libclntsh.so: undefined reference to `nztSetAppDefaultLocation'
/usr/lib/oracle/11.2/client/lib//libclntsh.so: undefined reference to`nzos_DisableClientAuthentication'
/usr/lib/oracle/11.2/client/lib//libclntsh.so: undefined reference to `nzos_Create_Ctx'
/usr/lib/oracle/11.2/client/lib//libclntsh.so: undefined reference to`nzgbllsm_location_shared_memory'
... 90 lines skipped
/usr/lib/oracle/11.2/client/lib//libclntsh.so: undefined reference to `nzos_setCertValPolicy'
/usr/lib/oracle/11.2/client/lib//libclntsh.so: undefined reference to`nzssGSL_GetSecretLength'
/usr/lib/oracle/11.2/client/lib//libclntsh.so: undefined reference to `B_DigestFinal'
collect2: ld returned 1 exit status
['/usr/bin/g++', 'default/test_1.o', '-o', '/tmp/111/node-db-oracle/build/.conf_check_0/testbuild/default/testprog', '-L/usr/lib/oracle/11.2/client/lib/', '-locci', '-lclntsh']
command returned 'Build failed:  -> task failed (err #1): \n\t{task: cxx_link test_1.o -> testprog}'Missing include files for OCI
--- cut ---

**Comment by mvtm** [comment]
patch:

<pre>
node-db-oracle# git diff
diff --git a/wscript b/wscript
index b1c87ce..0f6d11c 100644
--- a/wscript
+++ b/wscript
@@ -38,7 +38,7 @@ def configure(conf):
   if oci_lib:
       conf.env.append_unique('LINKFLAGS', [ '-L' + oci_lib ])
 
-  conf.env.append_unique('LINKFLAGS', ['-locci', '-lclntsh'])
+  conf.env.append_unique('LINKFLAGS', ['-locci', '-lclntsh','-lnnz11'])
   conf.check(header_name="occi.h", errmsg="Missing include files for OCI", mandatory=True)
   conf.check_cxx(lib="occi", errmsg="Missing libocci", mandatory=True)
</pre>

**Comment by mariano** [comment]
Fixed in a50f488f5d6f907425b4

Thanks!

**Comment by jefmsmit** [comment]
This fix broke the install on Mac OSX since there are no 11g instantclient downloads for the Mac yet. I fixed it by:
ln -s libnnz10.dylib libnnz11.dylib

Kinda cheating I realize, but it worked :)

**Comment by josecardozo** [comment]
Hi jefmsmit, thank you for the tip.
